server:
    port: 9000
    
spring:
    data:
        mongodb:
            host: 192.168.1.111
            port: 27017
            database: ourproject
            username: our
            password: our
    freemarker:
        template-loader-path: classpath:/templates
    mvc:
        static-path-pattren: /static/**